substitutions:
  # Core
  node_name: irtuya
  name: "IR Tuya"
  board: generic-bk7231n-qfn32-tuya

  # Climate
  climate_name: "${name} Toshiba AC"
  climate_sensor_id: climate_temp_sensor
  # climate_sensor_entity_id: sensor.efekta_air_monitor_midroom_temperature # Midroom
  # wifi_static_ip: 192.168.1.213 # Midroom
  climate_sensor_entity_id: sensor.efekta_air_monitor_bedroom_temperature # Bedroom
  wifi_static_ip: 192.168.1.212 # Bedroom

bk72xx:
  board: $board

packages:
  ir_toshiba_ac: !include packages/ir_toshiba_ac.yaml

  base: !include packages/base.yaml

wifi:
  output_power: 20dB
  # fast_connect: true

  manual_ip:
    static_ip: $wifi_static_ip
    gateway: 192.168.1.1
    subnet: 255.255.254.0

  # Changing node name https://esphome.io/components/esphome.html#changing-esphome-node-name
  # use_address: ircontrol.local

captive_portal:

# Enable logging
logger:

remote_transmitter:
  pin: P7
  carrier_duty_percent: 50%

sensor:
  - platform: homeassistant
    id: $climate_sensor_id
    entity_id: $climate_sensor_entity_id
