substitutions:
  project_version: "2024.1.3"
  # name of the node.
  node_name: tioncontrol
  name: TionControl
  # name for main climate entity and prefix for all others.
  friendly_name: $name
  # add suffix for node name to have one firmware for many devices.
  node_add_mac_suffix: "false"
  project_source_refresh: 1s
  vport_source_refresh: 1s

packages:
  tion:
    url: https://github.com/dentra/esphome-tion
    ref: 2024.1.3 # cant use substitutions here
    files:
      ## Enable additional WiFi signal sensor. Comment next line to disable.
      - packages/wifi_signal.yaml
      ## Enable additional Uptime sensor. Comment next line to disable.
      - packages/uptime.yaml
      ## Enable additional Restart button. Comment next line to disable.
      - packages/restart.yaml
      ## Base climate definition. Do not comment or move or remove.
      - packages/tion_4s_climate.yaml
      ## Enable maximum target temperature to 30°C. Comment next line to disable.
      - packages/tion_temperature30c.yaml
      ## Enable heat_cool mode to workaraund when using Home Assistant turn_on service.
      - packages/tion_enable_heat_cool.yaml
      ## Uncomment next line to enable additional energy sensor.
      - packages/tion_energy.yaml
      ## Common configuration settings. Do not comment or move or remove.
      - packages/base.yaml
      # change to esp32_s3.yaml/esp32_c3.yaml to use with ESP32-S2/ESP32-C3 chip or change to esp32.yaml to use with ESP32 chip.
      - packages/esp32_s2.yaml
      ## Uncomment next line to enable additional internal timers support.
      # - packages/tion_4s_timers.yaml
      ## Uncomment next line to enable monitor internal ESP temperature.
      # - packages/esp32_temperature.yaml
      ## Uncomment next line to enable additional debug information.
      # - packages/debug.yaml

  base: !include packages/base.yaml

# Virtual port configuration
vport:
  - platform: tion_4s_uart
    id: tion_uart_vport
    uart_id: uart_tion
    ## Optional, Interval between sending commmands. Set to 0ms to send one command per loop.
    # command_interval: 20ms
    ## Optional, Command queue size. Default: 10.
    # command_queue_size: 16
    ## Optional, Interval between sending heartbeat commands. Default: 5s.
    # heartbeat_interval: 5s

# Main climate component configuration.
climate:
  - id: !extend tion_climate
    # Required, the name of climate entity
    name: "${name}"
    # Optional, virtual port id. Default: autodetect
    vport_id: tion_uart_vport
    # Optional, Temperatire of air before heater, °C (celsius).
    outdoor_temperature:
      name: "${name} Outdoor Temperature"
    # Optional, Buzzer control switch.
    buzzer:
      name: "${name} Buzzer"
    # Optional, Led control switch.
    led:
      name: "${name} Led"
    # Optional, Heater power, W (watt).
    heater_power:
      name: "${name} Heater power"
    # Optional, Total airflow counter, m³ (cubic meters).
    airflow_counter:
      name: "${name} Airflow counter"
    # Optional, Recirculation control switch.
    recirculation:
      name: "${name} Recirculation"
    # Optional, Current productivity, m³/h (cubic meters per hour).
    productivity:
      name: "Productivity"
    # Optional, Filter time left counter, days.
    filter_time_left:
      name: "${name} Filter Time Left"
    # Optional, Filter warning state.
    filter_warnout:
      name: "${name} Filter Warnout"
    # Optional, Tion firmware version.
    version:
      name: "${name} Version"
    # Optional, Enable presets. Default: <empty> (no presets)
    # Available configurable presets: home, away, boost, comfort, eco, sleep, activity.
    # Defaults:
    #   home    : { fan_speed: 2, target_temperature: 20, gate_position: auto, mode: heat }
    #   away    : { fan_speed: 1, target_temperature: 10, gate_position: auto, mode: fan_only }
    #   boost   : { fan_speed: 6, target_temperature: 10, gate_position: auto, mode: fan_only }
    #   comfort : { fan_speed: 2, target_temperature: 23, gate_position: auto, mode: heat }
    #   eco     : { fan_speed: 1, target_temperature: 16, gate_position: auto, mode: heat }
    #   sleep   : { fan_speed: 1, target_temperature: 18, gate_position: auto, mode: heat }
    #   activity: { fan_speed: 3, target_temperature: 18, gate_position: auto, mode: heat }
    # Boost is a special preset that runs for a period defined by boost_time and then switches back to the previous preset.
    # Available mode:
    #  * off - define but disable preset
    #  * heat - enable heater
    #  * fan_only - fan only
    # Available gate_position (this option is optional):
    #  * auto - use current gate position
    #  * outdoor - set gate position to outdoor air intake (3S and 4S only)
    #  * indoor - set gate position to indoor air intake (3S and 4S only)
    #  * mixed - set gate position to mixed air intake (3S only)
    presets:
      boost: { fan_speed: 4, target_temperature: 12, mode: fan_only }
      activity: { fan_speed: 3, target_temperature: 18, mode: heat_cool }
      home: { fan_speed: 2, target_temperature: 20, mode: heat_cool }
      eco: { fan_speed: 1, target_temperature: 18, mode: heat_cool }
      away: { fan_speed: 1, target_temperature: 12, mode: heat_cool }
      sleep: { fan_speed: 1, target_temperature: 20, mode: heat_cool }
    # Optional, configure boost time
    boost_time:
      name: "${name} Boost Time"
    # Optional, display remaining boost time
    boost_time_left:
      name: "${name} Boost Time Left"
    # Optional, How often query device state. Default: 60s.
    update_interval: 10s
    # Optional, reset filter button
    reset_filter:
      name: "${name} Reset Filter"
    # Optional, reset filter confirmation. When off then reset_filter will not work.
    reset_filter_confirm:
      name: "Reset Filter Confirm"
    # Optional, Informs about get state problem from breezer.
    state_warnout:
      name: "State Warnout"
    # Optional, Timeout when state_warnout will be informed. Default: 3s.
    state_timeout: 3s
    # Optional, Timeout to combine update operations. Default: 200ms.
    batch_timeout: 200ms
    # Optional, Reports Tion's errors (EC) and warnings (WS).
    errors:
      name: "Errors"
