substitutions:
  node_name: tioncontrol
  name: TionControl
  board: lolin_s2_mini

esp32:
  board: $board

packages:
  tion:
    url: https://github.com/dentra/esphome-tion
    ref: master # cant use substitutions here
    files:
      ## Enable additional WiFi signal sensor. Comment next line to disable.
      - packages/wifi_signal.yaml
      ## Enable additional Uptime sensor. Comment next line to disable.
      - packages/uptime.yaml
      ## Uncomment next line to enable additional restart button.
      # - packages/restart.yaml
      ## Uncomment next line to enable monitor internal ESP temperature.
      # - packages/esp32_temperature.yaml
      ## Uncomment next line to enable additional debug information.
      # - packages/debug.yaml

  # framework_arduino: !include packages/framework_arduino.yaml
  framework_idf: !include packages/framework_idf.yaml
  base: !include packages/base.yaml

  tion4s_uart: !include packages/tion4s_uart.yaml

# lolin_s2_mini specific
uart:
  id: uart_bus
  tx_pin: 20
  rx_pin: 19
  baud_rate: 9600
