substitutions:
  board: lolin_s2_mini
  tx_pin: "20"
  rx_pin: "19"
  baud_rate: "9600"

esphome:
  platformio_options:
    board_build.flash_mode: dio
    build_flags:
      - -std=gnu++17
    build_unflags:
      - -std=gnu++11

esp32:
  board: $board
  framework:
    type: esp-idf

wifi:
  power_save_mode: none

logger:
  # Make sure logging is not using usb cdc
  hardware_uart: UART0

uart:
  - id: uart_tion
    tx_pin: $tx_pin
    rx_pin: $rx_pin
    baud_rate: $baud_rate
